Repository ManageIQ/manageiq-providers-nsxt, pull requests merged in 2020-05, with the labels that each got.

#3 added rubocop channel to code climate configuration
  .codeclimate.yml
Labels: bug

#5 Remove Translation Badge
  README.md
Labels: developer

#7 Delete unused zanata.xml file
  zanata.xml
Labels: cleanup
