Repository ManageIQ/manageiq-providers-nsxt, pull requests merged in 2020-10, with the labels that each got.

#20 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#22 Added API support for the NSX-T Data Center Federation/Global Manager
  app/models/manageiq/providers/nsxt/inventory/collector/network_manager.rb
  app/models/manageiq/providers/nsxt/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nsxt/inventory/parser/network_manager.rb
  app/models/manageiq/providers/nsxt/manager_mixin.rb
  app/models/manageiq/providers/nsxt/nsxt_client.rb
  app/models/manageiq/providers/nsxt/nsxt_client/rest.rb
  spec/models/manageiq/providers/nsxt/network_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/nsxt/network_manager/refresher.yml
Labels: enhancement

#21 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-nsxt.gemspec
Labels: developer, enhancement

#23 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
