Repository ManageIQ/manageiq-providers-nsxt, pull requests merged in 2020-11, with the labels that each got.

#26 Visibility of Nsxt new buttons
  app/assets/application_helper/button/any_nsxt_network_manager.rb
  app/assets/application_helper/button/belongs_to_nsxt_network_manager.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/cloud_network_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/cloud_networks_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/security_groups_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policy_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policy_rule_center.rb
  app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policy_rules_center.rb
Labels: enhancement

#28 Drop gettext initializer
  config/initializers/gettext.rb
Labels: cleanup

#29 [KASPAROV] yarn: lock versions by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies
