Repository ManageIQ/manageiq-providers-nsxt, pull requests merged in 2021-12, with the labels that each got.

#51 Replace PF react component with carbon
  app/javascript/components/cloud-networks/delete-nsxt-cloud-network-form.jsx
  app/javascript/components/security-groups/delete-nsxt-security-group-form.jsx
  app/javascript/components/security-policies/delete-nsxt-security-policy-form.jsx
  app/javascript/components/security-policy-rules/delete-nsxt-security-policy-rule-form.jsx
Labels: enhancement

#52 update yarn.lock file to remove PF react
  yarn.lock
Labels: technical debt

#53 Remove react-ui-components package
  package.json
  yarn.lock
Labels: technical debt

#50 converting supported_for_create to supports :create
  app/models/manageiq/providers/nsxt/network_manager.rb
Labels: refactoring
