Repository ManageIQ/manageiq-providers-nsxt, pull requests merged in 2021-03, with the labels that each got.

#36 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#37 Add CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#34 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-nsxt_network_manager_refresh.target
  build/systemd_units/manageiq-providers-nsxt_network_manager_refresh@.service
Labels: technical debt
