Repository ManageIQ/manageiq-providers-nsxt, pull requests merged in 2022-02, with the labels that each got.

#64 Remove Hakiri
  README.md
Labels: cleanup, developer

#65 Remove jest package
  package.json
  yarn.lock
Labels: technical debt

#66 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-nsxt.gemspec
Labels: developer, test

#58 Update node version
  package.json
Labels: dependencies

#69 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
